config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions",
    passwords: "admin/passwords",
    registrations: "admin/registrations"
  }

  namespace :admin do
    root to: "homes#top"
    resources :categories, only: [:index, :create, :edit, :update]
    resources :recipes, except: [:destroy, :new ,:create]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :stores, except: [:destroy] do
      resources :recipes, only: [:new, :create]
        member do
          get :recipes
        end

    end
  end

  # 顧客用

  devise_for :customers,skip: [:passwords],controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :arrange_recipes, except: [:destroy, :new ,:create]
    resources :stores, only: [:index,:show]

    resources :customers, only: [:show,:edit,:update] do
      collection do
    	get 'quit'
    	patch 'out'
    	end
    end


    resources :recipes, only: [:index, :show] do
      resources :arrange_recipes, only: [:new, :create]
      member do
        get :arrange_recipes
      end
      resources :post_comments, only: [:create, :destroy, :show]
      resources :bookmarks, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get :bookmarks
      end
    end


    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :image

  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarks_recipes, through: :bookmarks, source: :recipe
  has_many :arrange_recipes, dependent: :destroy
  
  with_options presence: true do
    validates :name
    validates :email
  end
  
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  def get_profile_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image1.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  

  def own?(object)
    id == object.customer_id
  end
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer), notice: '会員情報を更新しました。'
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name,  :email, :is_deleted)
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>会員ID</th>
      <th>ニックネーム</th>
      <th>メールアドレス</th>
      <th>会員ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% customers.each do |customer| %>
      <tr>
        <td class="info col-xs-1">
          <%= customer.id %>
        </td>
        <td class="text-left">
          <%= link_to customer.name,admin_customer_path(customer) %>
        </td>
        <td class="text-left">
          <%= customer.email %>
        </td>
        <td class="col-xs-2">
          <% if customer.is_deleted == true %>
          <p class="text-secondary">退会</p>
          <% else %>
          <p class="text-success">有効</p>
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/admin/customers/edit.html.erb
<div class="container">
  <h2 class="text-center m-5"><%= @customer.name %>さんの会員情報編集</h2>
  <div class="row d-flex justify-content-center">

  <%= form_with model: @customer, url: admin_customer_path, method: :patch, local: true do |f| %>
    
      <div class="form-group row">
        <%= f.label :"会員ID", class: "col-sm-6" %>
        <%= f.label :"#{@customer.id}" %>
      </div>
      <div class="form-group row">
        <%= f.label :"ニックネーム", class: "col-sm-6 control-label" %>
        <%= f.text_field :name, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-group row">
        <%= f.label :"メールアドレス", class: "col-sm-6 control-label" %>
        <%= f.text_field :email, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :"会員ステータス", class: "form_label my-3" %>
        <%= f.radio_button :is_deleted, false %>
        <%= f.label :is_deleted, "有効",class:"form_label"%>
        <%= f.radio_button :is_deleted, true %>
        <%= f.label :is_deleted, "退会",class:"form_label" %>
      </div>
    
      <div class="form-group col-xs-9 d-flex justify-content-around">
        <%= f.submit '変更を保存する' ,class: "btn btn-success mb-5" %>
      </div>

  <% end %>

  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
 
  <div class="row mt-5">
    <h2 class="mx-auto mb-5">会員一覧</h2>
  </div>
  
  <div class="row d-flex justify-content-center">
    <%= render 'index', customers: @customers%>
 </div>
 <div class="d-flex justify-content-center"><%= paginate(@customers)%></div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h2 class="mt-5 text-center"><%= @customer.name %>さんの会員詳細</h2>
    <div class="row m-5">
      <div class="col-8 offset-3">
        <table class="table table-bordered", style="width: 70%">
          <tr>
            <th class="bg-light">会員ID</th>
            <td><%= @customer.id%></td>
          </tr>
          <tr>
            <th class="bg-light">ニックネーム</th>
            <td><%= @customer.name %></td>
          </tr>
          
          <tr>
            <th class="bg-light">メールアドレス</th>
            <td><%= @customer.email%></td>
          </tr>
          <tr>
            <th class="bg-light">会員ステータス</th>
            <% if @customer.is_deleted == true %>
             <td class="text-secondary">退会</td>
            <% else %>
             <td class="text-success">有効</td>
            <% end %>
          </tr>
        </table>
        <div class="d-flex mx-auto">
          <p><%= link_to "編集する",edit_admin_customer_path, class:"btn btn-success"%></p>
        </div>
      </div>
  　</div>
 </div>