config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions",
    passwords: "admin/passwords",
    registrations: "admin/registrations"
  }

  namespace :admin do
    root to: "homes#top"
    resources :categories, only: [:index, :create, :edit, :update]
    resources :recipes, except: [:destroy, :new ,:create]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :stores, except: [:destroy] do
      resources :recipes, only: [:new, :create]
        member do
          get :recipes
        end

    end
  end

  # 顧客用

  devise_for :customers,skip: [:passwords],controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :arrange_recipes, except: [:destroy, :new ,:create]
    resources :stores, only: [:index,:show]

    resources :customers, only: [:show,:edit,:update] do
      collection do
    	get 'quit'
    	patch 'out'
    	end
    end


    resources :recipes, only: [:index, :show] do
      resources :arrange_recipes, only: [:new, :create]
      member do
        get :arrange_recipes
      end
      resources :post_comments, only: [:create, :destroy, :show]
      resources :bookmarks, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get :bookmarks
      end
    end


    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord

  has_one_attached :image

  belongs_to :category
  has_many :recipes, dependent: :destroy

  with_options presence: true do
    validates :store_name
    validates :introduction
    validates :address
    validates :telephone_number
    validates :opening_hour
  end

  validates :introduction, length: { maximum: 80 }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def self.category(category_id)
  　if search
  　　Store.where(category_id: category_id)
  　else
  　　Store.all
  　end
  end
end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < ApplicationController
  
  before_action :authenticate_admin!

  def index
    @stores = Store.page(params[:page]).per(10)
  end

  def new
    @store = Store.new
  end

  def show
    @store = Store.find(params[:id])
  end

  def edit
    @store = Store.find(params[:id])
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to  admin_store_path(@store)
    else
      render :new
    end
  end
  
  def recipes
      @store = Store.find(params[:id])
      @recipes = @store.recipes.page(params[:page]).per(10)
    
  end

  def update
    @store = Store.find(params[:id])
    if @store.update(store_params)
    redirect_to admin_store_path(@store)
    else
    render:edit
    end
  end

  private

  def store_params
    params.require(:store).permit(:image, :store_name, :introduction, :address, :telephone_number, :opening_hour, :category_id)
  end

  
end

app/helpers/admin/stores_helper.rb
module Admin::StoresHelper
end

app/views/admin/stores/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>店舗ID</th>
      <th>店名</th>
      <th>カテゴリ</th>
      <th>住所</th>
    </tr>
  </thead>

  <tbody>
    <% stores.each do |store| %>
      <tr>
        <td class="info col-xs-1">
          <%= store.id %>
        </td>
        <td class="text-left">
          <%= link_to store.store_name,admin_store_path(store) %>
        </td>
        <td class="text-left">
          <%= store.category.name %>
        </td>
        <td class="text-left">
          <%= store.address %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/admin/stores/edit.html.erb
<div class="container">
  <h2 class="text-center my-5">店舗編集</h2>
  <div class="row">
    <div class="col-8 offset-2 mb-5">
      <%= form_with model: @store, url: admin_store_path, local: true do |f| %>
      <table>
        <tr>
          <div class="form-group">
            <%= f.label :店舗画像, class:"form_label"%>
            <%= f.file_field :image, accept: "image/*",class:"mb-3 ml-3"%>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :店名, class:"form_label" %>
            <%= f.text_field :store_name, placeholder:"店名", autofocus: true, class:"form-control mb-3" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :紹介文, class:"form_label" %>
            <%= f.text_area :introduction, size: "50x5",  autofocus: true, class:"form-control form-control-lg mb-3" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :カテゴリ, class:"form_label" %>
            <%= f.collection_select :category_id, Category.all, :id, :name, :prompt => "--選択してください--", class:"form-select-lg" %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :住所, class:"form_label" %>
            <%= f.text_field :address, autofocus: true, size: "50", class: 'form-control mb-3' %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :電話番号, class:"form_label" %>
            <%= f.telephone_field :telephone_number, class:"form-control mb-3", autofocus: true %>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <%= f.label :営業時間, class:"form_label" %>
            <%= f.text_field :opening_hour, placeholder:"00:00〜00:00", class: "form-control mb-3" %>
          </div>
        </tr>
        <tr>
          <div class="form-action d-flex justify-content-around">
            <%= f.submit "変更を保存", class:"btn btn-success" %>
          </div>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/stores/index.html.erb
<div class="container">
  <div class="row mt-5">
    <h2 class="mx-auto mb-5">店舗一覧</h2>
  </div>

  <div class="row d-flex justify-content-center">
    <%= render 'index', stores: @stores%>
  </div>

 <div class="d-flex justify-content-center mb-4"><%= paginate(@stores)%></div>

  <div class="row d-flex justify-content-center">
    <p><%= link_to "店舗を新規登録", new_admin_store_path, class: "btn btn-success mb-5" %></p>
  </div>
</div>

app/views/admin/stores/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-sm-8 px-sm-0 offset-sm-1 text-center">
      <h2>店舗新規登録</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 px-sm-0 mx-auto mb-5">
      <%= form_with model: @store, url: admin_stores_path, local: true do |f| %>
        <%= render 'admin/shared/error_messages', object: f.object %>
      <table>
        <tr>
          <div class="form-group">
            <th><%= f.label :店舗画像 %></th>
            <th><%= f.file_field :image, accept: "image/*" %></th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :店名 %></th>
            <td><%= f.text_field :store_name, autofocus: true, class:"rounded", placeholder:"店名" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :紹介文 %></th>
            <td><%= f.text_area :introduction, size: "50x5", placeholder:"ここに説明文を記述します" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :カテゴリ %></th>
            <td><%= f.collection_select :category_id, Category.all, :id, :name, :prompt => "--選択してください--" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :住所 %></th>
            <td><%= f.text_field :address, autofocus: true, class: 'rounded', size: "50", placeholder: "東京都渋谷区代々木神園町0-0" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :電話番号 %></th>
            <td><%= f.telephone_field :telephone_number, class:"rounded", autofocus: true, placeholder:"00000000000" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :営業時間 %></th>
            <td><%= f.text_field :opening_hour, class:"rounded", placeholder:"00:00〜00:00" %></td>
          </div>
        </tr>

        <tr>
          <div class="form-action">
            <th><%= f.submit "新規登録", class:"btn btn-bloc btn-success mt-4" %></th>
          </div>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/stores/recipes.html.erb
<div class="container">
  <div class="row mt-5">
    <h2 class="mx-auto mb-5">レシピ一覧</h2>
  </div>
  
  <div class="row d-flex justify-content-center">
    <%= render 'admin/recipes/index', recipes: @recipes%>
  </div>
  <div class="d-flex justify-content-center"><%= paginate(@recipes)%></div>
</div>

app/views/admin/stores/show.html.erb
<div class="container">
  <div class="mt-5">
    <h2 class="mb-4 text-center text-color rounded-pill pb-2 pt-2"><%= @store.store_name %>さんの店舗詳細</h2>
  </div>

  <div class="row align-items-center m-5">
    <div class="col-12 text-center mb-3">
      <%= image_tag @store.get_image(350,250) %>
    </div>
  </div>

  <div class="row m-5">
    <div class="col-12 offset-2">
      <table class="table table-bordered", style="width: 70%">
        <tbody>
          <tr>
            <td class="col-2 bg-light">店舗ID</td>
            <td><%= @store.id%></td>
          </tr>
          <tr>
            <td class="bg-light">店名</td>
            <td><%= @store.store_name %></td>
          </tr>
          <tr>
            <td class="bg-light">紹介文</td>
            <td><%= @store.introduction %></td>
          </tr>
          <tr>
            <td class="bg-light">カテゴリ</td>
            <td><%= @store.category.name %></td>
          </tr>
          <tr>
            <td class="bg-light">住所</td>
            <td><%= @store.address %></td>
          </tr>
          <tr>
            <td class="bg-light">電話番号</td>
            <td><%= @store.telephone_number %></td>
          </tr>
          <tr>
            <td class="bg-light">営業時間</td>
            <td><%= @store.opening_hour %></td>
          </tr>
        </tbody>
      </table>
      <div class="row mt-5">
    　　<p><%= link_to "店舗情報を編集する", edit_admin_store_path, class: "btn btn-success" %></p>
  　　</div>
  　　<div class="row mt-1">
    　　<p>  <%= link_to "店舗のレシピ一覧を見る", recipes_admin_store_path(@store), class: "btn btn-warning" %></p>
  　　</div>
  　　<div class="row mb-1">
    　　<p><%= link_to "レシピを投稿する", new_admin_store_recipe_path(@store), class: "btn btn-primary" %></p>
  　　</div>
    </div>
  </div>
</div>