config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions",
    passwords: "admin/passwords",
    registrations: "admin/registrations"
  }

  namespace :admin do
    root to: "homes#top"
    resources :categories, only: [:index, :create, :edit, :update]
    resources :recipes, except: [:destroy, :new ,:create]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :stores, except: [:destroy] do
      resources :recipes, only: [:new, :create]
        member do
          get :recipes
        end

    end
  end

  # 顧客用

  devise_for :customers,skip: [:passwords],controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :arrange_recipes, except: [:destroy, :new ,:create]
    resources :stores, only: [:index,:show]

    resources :customers, only: [:show,:edit,:update] do
      collection do
    	get 'quit'
    	patch 'out'
    	end
    end


    resources :recipes, only: [:index, :show] do
      resources :arrange_recipes, only: [:new, :create]
      member do
        get :arrange_recipes
      end
      resources :post_comments, only: [:create, :destroy, :show]
      resources :bookmarks, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get :bookmarks
      end
    end


    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :recipes, dependent: :destroy
  has_many :stores
  
  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @categories = Category.all
    @category = Category.new
  end
  
  def edit
     @category = Category.find(params[:id])
  end
  
  def create
    @category = Category.new(category_params)
		if @category.save
		  redirect_to admin_categories_path
		else
		  @categories = Category.all
		  render :index
		end
  end
  
  def update
    @category = Category.find(params[:id])
    
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render :edit
    end
  end
  
  private

	def category_params
	  params.require(:category).permit(:name)
	end
  
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col">
            <h2 class="text-center">カテゴリ編集</h2>
        </div>
    </div>

    <div class="row mt-4">
      <div class="col-1"></div>
        <div class="col-5">
          <%= form_with model: @category,url: admin_category_path, method: :patch, local: true do |f| %>
          <%= f.label "カテゴリ名", class: "ms-5" %>
          <%= f.text_field :name, class: "ms-5" %>
          <%=f.submit "変更を保存", class:"btn btn-success ms-5 fs-5" %>
          <% end %>
        </div>
    </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
    <div class="row text-center">
      <div class="col-md-12 mt-5">
        <h2>カテゴリ一覧・追加</h2>
      </div>
    </div>
    <div class="row my-5 d-flex justify-content-center">
        <div class="col-xs-12">
            <%= form_with model: @category,url: admin_categories_path,method: :post, remote: true do |f| %>
             <%= f.label :name, "カテゴリ名" %>
             <%= f.text_field :name, id: "form" %>
             <%= f.submit "新規登録", class:"btn btn-primary ml-4 py-1" %>
            <% end %>
        </div>
    </div>

    <div class="row my-5 justify-content-center">
      <div class="col-lg-5 mt-3">
        <table class="table">
          <thead>
            <tr>
              <th>カテゴリ</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td></td>
              <td align="right"><%= link_to "　編集する　", edit_admin_category_path(category), class: "btn btn-success" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
</div>