config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions",
    passwords: "admin/passwords",
    registrations: "admin/registrations"
  }

  namespace :admin do
    root to: "homes#top"
    resources :categories, only: [:index, :create, :edit, :update]
    resources :recipes, except: [:destroy, :new ,:create]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :stores, except: [:destroy] do
      resources :recipes, only: [:new, :create]
        member do
          get :recipes
        end

    end
  end

  # 顧客用

  devise_for :customers,skip: [:passwords],controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :arrange_recipes, except: [:destroy, :new ,:create]
    resources :stores, only: [:index,:show]

    resources :customers, only: [:show,:edit,:update] do
      collection do
    	get 'quit'
    	patch 'out'
    	end
    end


    resources :recipes, only: [:index, :show] do
      resources :arrange_recipes, only: [:new, :create]
      member do
        get :arrange_recipes
      end
      resources :post_comments, only: [:create, :destroy, :show]
      resources :bookmarks, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get :bookmarks
      end
    end


    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arrange_ingredient.rb
class ArrangeIngredient < ApplicationRecord
  
  belongs_to :arrange_recipe, optional: true
  
  with_options presence: true do
    validates :name
    validates :amount
  end

  
end

app/models/arrange_procedure.rb
class ArrangeProcedure < ApplicationRecord

  belongs_to :arrange_recipe

  with_options presence: true do
    validates :body
  end

end

app/models/arrange_recipe.rb
class ArrangeRecipe < ApplicationRecord

  has_one_attached :image
  belongs_to :recipe
  belongs_to :customer
  has_many :arrange_procedures, dependent: :destroy
  has_many :arrange_ingredients, dependent: :destroy

  accepts_nested_attributes_for :arrange_procedures, allow_destroy: true
  accepts_nested_attributes_for :arrange_ingredients, allow_destroy: true

  with_options presence: true do
    validates :serving
    validates :title
    validates :arrange_ingredients
    validates :arrange_procedures
  end

  validates :comment, length: { maximum: 80 }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
  
  validates_uniqueness_of :recipe_id, scope: :customer_id
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :recipes, dependent: :destroy
  has_many :stores
  
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :image

  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarks_recipes, through: :bookmarks, source: :recipe
  has_many :arrange_recipes, dependent: :destroy
  
  with_options presence: true do
    validates :name
    validates :email
  end
  
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  def get_profile_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image1.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  

  def own?(object)
    id == object.customer_id
  end
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :customer
  belongs_to :recipe

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  
  belongs_to :recipe, optional: true
  
  with_options presence: true do
    validates :name
    validates :amount
  end
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :customer
  belongs_to :recipe
  
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :recipe

  with_options presence: true do
    validates :body
  end

end

app/models/recipe.rb
class Recipe < ApplicationRecord

  has_one_attached :image
  belongs_to :category
  belongs_to :store
  has_many :procedures, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :arrange_recipes, dependent: :destroy

  accepts_nested_attributes_for :procedures, allow_destroy: true
  accepts_nested_attributes_for :ingredients, allow_destroy: true


  with_options presence: true do
    validates :serving
    validates :title
    validates :ingredients
    validates :procedures
  end

  validates :comment, length: { maximum: 80 }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def get_profile_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image1.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end


  def post_commented_by?(customer)
    post_comments.exists?(customer_id: customer.id)
  end

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def bookmarked_by?(customer)
    bookmarks.exists?(customer_id: customer.id)
  end
end

app/models/store.rb
class Store < ApplicationRecord

  has_one_attached :image

  belongs_to :category
  has_many :recipes, dependent: :destroy

  with_options presence: true do
    validates :store_name
    validates :introduction
    validates :address
    validates :telephone_number
    validates :opening_hour
  end

  validates :introduction, length: { maximum: 80 }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def self.category(category_id)
  　if search
  　　Store.where(category_id: category_id)
  　else
  　　Store.all
  　end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/helpers/admin/stores_helper.rb
module Admin::StoresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <p><%= object.errors.count %> 件のエラーが発生しました</p>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-secondary text-white pt-5 pb-4">
  <div class="container">
    <div class="row">
      <div class="mx-auto">
        <p id="copyright">© 2022 Rumi Hirose All Rights Reserved</p>
      </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <% if admin_signed_in?  %>
        <%= link_to "おうちdeお店ごはん", admin_root_path, class:"header-title navbar-brand btn btn-outline-secondary btn-lg mx-3 my-1" %>
      <% else %>
        <%= link_to "おうちdeお店ごはん", root_path, class:"header-title navbar-brand btn btn-outline-secondary btn-lg mx-3 my-1" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if customer_signed_in? %>
        <li class="nav-item">
          <%= link_to 'マイページ', customer_path(current_customer.id), class: "btn btn-outline-secondary mx-3 my-1" %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary mx-3 my-1" %>
        </li>
        <% elsif admin_signed_in? %>
        <li class="nav-item">
          <%= link_to ' 店舗一覧 ', admin_stores_path, class: "btn btn-outline-secondary mx-3 my-1" %>
        </li>
        <li class="nav-item">
          <%= link_to ' レシピ一覧 ', admin_recipes_path, class: "btn btn-outline-secondary mx-3 my-1" %>
        </li>
        <li class="nav-item">
          <%= link_to ' 会員一覧 ', admin_customers_path, class: "btn btn-outline-secondary mx-3 my-1" %>
        </li>
        <li class="nav-item">
          <%= link_to ' カテゴリ一覧 ', admin_categories_path, class: "btn btn-outline-secondary mx-3 my-1" %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary mx-3 my-1" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to ' About ',about_path,class: "btn btn-outline-secondary mx-3 my-1" %>
        </li>
        <li class="nav-item">
          <%= link_to ' 新規登録 ', new_customer_registration_path,class: "btn btn-outline-secondary mx-3 my-1" %>
        </li>
        <li class="nav-item">
          <%= link_to ' ログイン ', new_customer_session_path,class: "btn btn-outline-secondary mx-3 my-1" %>
        </li>
        <% end %>
        </ul>
      </div>
    </div>

  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>おうちdeお店ごはん</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/c7edd66cbf.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <main>
      <%= yield %>
    </main>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>

  </body>
</html>